version: "3"

services:
    zookeeper:
        image: jh12z/kafka-zookeeper
        ports:
            - 2181:2181
        volumes:
            - zookeeper_data:/tmp/zookeeper

    kafka:
        image: jh12z/kafka
        ports:
            - 9092:9092
        volumes:
            - kafka_data:/tmp/kafka-logs
    
    kafka-connect:
        image: jh12z/kafka-connect
        ports:
            - 8083:8083
    
volumes:
    kafka_data:
    zookeeper_data:
